<?php
//
$labelsArray = array(
    "email" => "Электронная почта",
    "login" => "Имя пользователя",
    "firstName" => "Имя",
    "lastName" => "Фамилия",
    "middleName" => "Отчество",
    "occupation" => "Должность",
    "phone" => "Телефон",
);
$profile = $this->profile;
?>
<div class="profile-container" id="profile-container">
    <?php
    if (!$profile) {
        ?>
        <p>Ошибка! Информация не найдена</p>
    <?php } else {
        ?>
        <div class="jumbotron">
            <div class="jumbotron-contents">
                <h1><?= $profile['lastName'] . '&nbsp;' . $profile['firstName'] . '&nbsp;' . $profile['middleName'] ?><small></small></h1>
                <p><?= $profile['login'] ?></p>
                <p><span class="badge badge-default"><?= $profile['status'] ?></span></p>
                <p class="lead"><a target="_blank" href="mailto:<?= $profile['email'] ?>"><span class="glyphicon glyphicon-envelope"></span> Отправить письмо</a></p>
                <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>
            </div>
        </div>     
        <?php foreach ($labelsArray as $key => $value) {
            ?>
            <div class="row"><div class="col-md-6"><label class="profile-element-label"><?= $value ?></label></div><div class="col-md-6"><p class="profile-element"><?= isset($profile[$key]) ? $profile[$key] : "" ?></p></div></div>
            <?php
        }
    }
    ?>        
</div>
<div class="profile-control-container">
    <p><a href="<?= $this->url('user\\admin/edit', array("id" => $profile['id'])) ?>" class="user-edit-link">Изменить</a></p>
</div>