<?php echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Панель администратора') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        
        <!-- Scripts /standart/ -->
         <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/Kendo/kendo.all.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
    </head>
    <body>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('admin') ?>">Панель администратора</a>
                </div>
                <div class="collapse navbar-collapse">
                        <?php // <-- Update this !!
echo $this->navigation('admin_navigation')->setAcl($this->acl)->setRole($this->currentRoles)
    ->menu()
    ->setMinDepth(0)
    ->setMaxDepth(0)
    ->setUlClass('nav navbar-nav')
    ->render();
?>    
                
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="wrapper">
        <div class="container">
                     <?php echo $this->content; ?>
                    </div> <!-- /container -->
                    <div class="push"></div>
</div>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
                <?php echo $this->inlineScript() ?>
    </body>
</html>
