<?php

namespace DoctrineORMModule\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140827142316 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE program_status_id_seq1 CASCADE");
        $this->addSql("DROP SEQUENCE program_financing_id_seq1 CASCADE");
        $this->addSql("DROP SEQUENCE program_indicator_id_seq1 CASCADE");
        $this->addSql("DROP SEQUENCE file_types_id_seq1 CASCADE");
        $this->addSql("DROP SEQUENCE program_stages_id_seq1 CASCADE");
        $this->addSql("DROP SEQUENCE program_id_seq1 CASCADE");
        $this->addSql("DROP SEQUENCE file_id_seq1 CASCADE");
        $this->addSql("ALTER TABLE file ALTER id DROP DEFAULT");
        $this->addSql("COMMENT ON COLUMN file.type IS NULL");
        $this->addSql("COMMENT ON COLUMN file.name IS NULL");
        $this->addSql("COMMENT ON COLUMN file.path IS NULL");
        $this->addSql("ALTER TABLE file_types ALTER id DROP DEFAULT");
        $this->addSql("ALTER TABLE program ALTER id DROP DEFAULT");
        $this->addSql("ALTER TABLE program ALTER npa TYPE INT");
        $this->addSql("ALTER TABLE program ALTER report TYPE INT");
        $this->addSql("ALTER TABLE program ALTER project TYPE INT");
        $this->addSql("ALTER TABLE program ALTER resolution TYPE INT");
        $this->addSql("ALTER TABLE program ALTER expertise TYPE INT");
        $this->addSql("COMMENT ON COLUMN program.performer IS NULL");
        $this->addSql("COMMENT ON COLUMN program.npa IS NULL");
        $this->addSql("COMMENT ON COLUMN program.report IS NULL");
        $this->addSql("COMMENT ON COLUMN program.status IS NULL");
        $this->addSql("COMMENT ON COLUMN program.author IS NULL");
        $this->addSql("COMMENT ON COLUMN program.project IS NULL");
        $this->addSql("COMMENT ON COLUMN program.resolution IS NULL");
        $this->addSql("COMMENT ON COLUMN program.expertise IS NULL");
        $this->addSql("COMMENT ON COLUMN program.name IS NULL");
        $this->addSql("COMMENT ON COLUMN program.reason IS NULL");
        $this->addSql("COMMENT ON COLUMN program.expected_results IS NULL");
        $this->addSql("COMMENT ON COLUMN program.goals IS NULL");
        $this->addSql("COMMENT ON COLUMN program.prediction IS NULL");
        $this->addSql("COMMENT ON COLUMN program.start_year IS NULL");
        $this->addSql("COMMENT ON COLUMN program.end_year IS NULL");
        $this->addSql("COMMENT ON COLUMN program.current_state IS NULL");
        $this->addSql("COMMENT ON COLUMN program.tasks IS NULL");
        $this->addSql("COMMENT ON COLUMN program.indicator_description IS NULL");
        $this->addSql("COMMENT ON COLUMN program.version IS NULL");
        $this->addSql("ALTER TABLE program_financing ALTER id DROP DEFAULT");
        $this->addSql("COMMENT ON COLUMN program_financing.program IS NULL");
        $this->addSql("COMMENT ON COLUMN program_financing.year IS NULL");
        $this->addSql("COMMENT ON COLUMN program_financing.budget IS NULL");
        $this->addSql("COMMENT ON COLUMN program_financing.external IS NULL");
        $this->addSql("COMMENT ON COLUMN program_financing.federal_budget IS NULL");
        $this->addSql("COMMENT ON COLUMN program_financing.growth IS NULL");
        $this->addSql("COMMENT ON COLUMN program_financing.current IS NULL");
        $this->addSql("ALTER TABLE program_indicator ALTER id DROP DEFAULT");
        $this->addSql("COMMENT ON COLUMN program_indicator.number IS NULL");
        $this->addSql("COMMENT ON COLUMN program_indicator.name IS NULL");
        $this->addSql("COMMENT ON COLUMN program_indicator.measure IS NULL");
        $this->addSql("COMMENT ON COLUMN program_indicator.current_value IS NULL");
        $this->addSql("COMMENT ON COLUMN program_indicator.year IS NULL");
        $this->addSql("COMMENT ON COLUMN program_indicator.final_value IS NULL");
        $this->addSql("ALTER TABLE program_stages ALTER id DROP DEFAULT");
        $this->addSql("COMMENT ON COLUMN program_stages.program IS NULL");
        $this->addSql("COMMENT ON COLUMN program_stages.description IS NULL");
        $this->addSql("ALTER TABLE program_status ALTER id DROP DEFAULT");
        $this->addSql("COMMENT ON COLUMN program_status.name IS NULL");
        $this->addSql("COMMENT ON COLUMN users.built_in IS 'Встроенный юзер'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE program_status_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE program_financing_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE program_indicator_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE file_types_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE program_stages_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE program_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE file_id_seq1 INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("COMMENT ON COLUMN users.built_in IS ''");
        $this->addSql("CREATE SEQUENCE program_financing_id_seq");
        $this->addSql("SELECT setval('program_financing_id_seq', (SELECT MAX(id) FROM program_financing))");
        $this->addSql("ALTER TABLE program_financing ALTER id SET DEFAULT nextval('program_financing_id_seq')");
        $this->addSql("CREATE SEQUENCE program_indicator_id_seq");
        $this->addSql("SELECT setval('program_indicator_id_seq', (SELECT MAX(id) FROM program_indicator))");
        $this->addSql("ALTER TABLE program_indicator ALTER id SET DEFAULT nextval('program_indicator_id_seq')");
        $this->addSql("CREATE SEQUENCE program_stages_id_seq");
        $this->addSql("SELECT setval('program_stages_id_seq', (SELECT MAX(id) FROM program_stages))");
        $this->addSql("ALTER TABLE program_stages ALTER id SET DEFAULT nextval('program_stages_id_seq')");
        $this->addSql("CREATE SEQUENCE program_status_id_seq");
        $this->addSql("SELECT setval('program_status_id_seq', (SELECT MAX(id) FROM program_status))");
        $this->addSql("ALTER TABLE program_status ALTER id SET DEFAULT nextval('program_status_id_seq')");
        $this->addSql("CREATE SEQUENCE program_id_seq");
        $this->addSql("SELECT setval('program_id_seq', (SELECT MAX(id) FROM program))");
        $this->addSql("ALTER TABLE program ALTER id SET DEFAULT nextval('program_id_seq')");
        $this->addSql("ALTER TABLE program ALTER npa TYPE BIGINT");
        $this->addSql("ALTER TABLE program ALTER report TYPE BIGINT");
        $this->addSql("ALTER TABLE program ALTER project TYPE BIGINT");
        $this->addSql("ALTER TABLE program ALTER resolution TYPE BIGINT");
        $this->addSql("ALTER TABLE program ALTER expertise TYPE BIGINT");
        $this->addSql("CREATE SEQUENCE file_types_id_seq");
        $this->addSql("SELECT setval('file_types_id_seq', (SELECT MAX(id) FROM file_types))");
        $this->addSql("ALTER TABLE file_types ALTER id SET DEFAULT nextval('file_types_id_seq')");
        $this->addSql("CREATE SEQUENCE file_id_seq");
        $this->addSql("SELECT setval('file_id_seq', (SELECT MAX(id) FROM file))");
        $this->addSql("ALTER TABLE file ALTER id SET DEFAULT nextval('file_id_seq')");
    }
}
