<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 * Version 0.6.2
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineORMModule',
        'Application',
        'Email',
        'User',
        'Kendo',
        'Acl',
        'Navigation',
        'Admin',
        'Log'
        ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
            ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php')
        )
    );
