<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class LogDocumentLogHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['importance'])) {
            $value = $data['importance'];
            $return = (string) $value;
            $this->class->reflFields['importance']->setValue($document, $return);
            $hydratedData['importance'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['category'])) {
            $value = $data['category'];
            $return = (string) $value;
            $this->class->reflFields['category']->setValue($document, $return);
            $hydratedData['category'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['url'])) {
            $value = $data['url'];
            $return = (string) $value;
            $this->class->reflFields['url']->setValue($document, $return);
            $hydratedData['url'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['text'])) {
            $value = $data['text'];
            $return = (string) $value;
            $this->class->reflFields['text']->setValue($document, $return);
            $hydratedData['text'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['timestamp'])) {
            $value = $data['timestamp'];
            $return = (int) $value;
            $this->class->reflFields['timestamp']->setValue($document, $return);
            $hydratedData['timestamp'] = $return;
        }
        return $hydratedData;
    }
}